name: Deployment for vue application

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5

      - name: Install packages
        run: npm i

      - name: Build project
        run: npm run build

      # fix this issue
      - name: Upload Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
